### ISSUE TITLE
Clarification about this repo?

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt-maven-resolver#1]
I can't get this project to build:

```bash
git clone git@github.com:sbt/sbt-maven-resolver.git
cd sbt-maven-resolver
sbt compile
…
[info] Compiling 11 Scala sources and 1 Java source to /Users/ryan/c/sbt-maven-resolver/target/scala-2.10/classes...
[error] /Users/ryan/c/sbt-maven-resolver/src/main/scala/sbt/MavenResolverConverter.scala:3: object librarymanagement is not a member of package sbt
[error] import sbt.librarymanagement.{ MavenCache, MavenRepository, UpdateOptions }
[error]            ^
[error] /Users/ryan/c/sbt-maven-resolver/src/main/scala/sbt/MavenResolverConverter.scala:5: not found: object UpdateOptions
[error] import UpdateOptions.ResolverConverter
[error]        ^
…
```

The instructions on the README seem to indicate that this code was a subtree of the SBT repo, and was dumped here; is that right?

I was looking to investigate some SBT Maven-resolution logic and ended up here, which I think is not what I want, but in any case thought I'd ask.

It seems like something here was used to create a sbt-maven-resolver artifact that [SBT optionally depends on](https://github.com/sbt/sbt/blob/v1.0.4/main/src/main/scala/sbt/Defaults.scala#L3001); some context on how that was created would be good, if it's easy. Thanks!

**Comment by eed3si9n** [comment]
> The instructions on the README seem to indicate that this code was a subtree of the SBT repo, and was dumped here; is that right?

Yes, you're right. Some interested party me or whoever probably need to update the code to follow up with changes made in sbt side.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-maven-resolver/pull/5
